# Generated by Django 3.1.5 on 2021-01-11 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_games_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='games',
        ),
    ]
