# Generated by Django 3.1.5 on 2021-01-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0003_delete_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('NA_Sales', models.IntegerField()),
                ('EU_Sales', models.IntegerField()),
                ('JP_Sales', models.IntegerField()),
                ('Other_Sales', models.IntegerField()),
                ('Global_Sales', models.IntegerField()),
            ],
        ),
    ]
